LEARNING_RATE = 1e-4

NUM_TRAIN_EPOCHS = 2

MAX_LENGTH = 512

WARMUP_STEPS = 60

EARLY_STOPPING_PATIENCE = 4

LOGGING_STEPS = 25
EVAL_STEPS = 50
SAVE_STEPS = 100

PER_DEVICE_TRAIN_BATCH_SIZE = 2
PER_DEVICE_EVAL_BATCH_SIZE = 2

GRADIENT_ACCUMULATION_STEPS = 16
GRADIENT_CHECKPOINTING = True

LR_SCHEDULE_TYPE = "cosine"

EVAL_STRATEGY = "steps"
LOGGING_STRATEGY = "steps"
SAVE_STRATEGY = "steps"

WEIGHT_DECAY = 0.01

SAVE_TOTAL_LIMIT = 3

OPTIM = "adamw_torch"

SEED = 42

FP16 = False
BF16 = True

REPORT_TO = "none"

REMOVE_UNUSED_COLUMNS = False

DATALOADER_PIN_MEMORY = False
DATALOADER_NUM_WORKERS = 2

LOAD_BEST_MODEL_AT_END = True

METRIC_FOR_BEST_MODEL = "eval_loss"

GREATER_IS_BETTER = False
